# Generated by Django 4.0.4 on 2022-04-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_cap',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
